swagger: "2.0"
info:
  title: Duolingo Leaderboards Unofficial API
  description: Unofficial API description for Duolingo Leaderboards.
  version: 1.0.0
host: duolingo-leaderboards-prod.duolingo.com
basePath: /
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  BearerAuth:
    type: basic

security:
  - BearerAuth: []

paths:
  /leaderboards/{leaderboardID}/users/{userID}:
    get:
      summary: Returns user information when not logged in.
      description: User information when not logged in.
      parameters:
        - in: path
          name: leaderboardID
          required: true
          type: string
          minimum: 1
          description: LeaderboardID
        - in: path
          name: userID
          required: true
          type: string
          minimum: 1
          description: UserID
      responses:
        200:
          description: A Users object.
          schema:
            $ref: '#/definitions/Leaderdoard'
        400:
          description: The specified user ID or leaderboard ID is invalid (e.g. not a number).
        404:
          description: A user with the specified ID was not found.
        default:
          description: Unexpected error

definitions:
  Leaderdoard:
    properties:
      active:
        $ref: '#/definitions/Active'
  Active:
    properties:
      rankings:
        type: array
        items:
          $ref: '#/definitions/Ranking'
  Ranking:
    properties:
      avatar_url: 
        type: string
      display_name:
        type: string
      score:
        type: number
      streak_extended_today:
        type: boolean
      user_id:
        type: integer
