swagger: "2.0"
info:
  title: Duolingo Unofficial API (Leaderboards)
  description: Unofficial API description for Duolingo.
  version: 1.0.0
host: duolingo-leaderboards-prod.duolingo.com
basePath: /
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header

security:
  - BearerAuth: []
  
paths:
  /leaderboards/{leaderboardID}/users/{userID}:
    $ref: "./operations/leaderboards.yaml"
